import { type File } from "@/components/FileSystem/FileUtils/types";
import { generateUniqueId } from "@/lib/utils";

export type Files = {
  Root: File & {
    entries: {
      System: File & {
        entries: {
          "File Manager": File;
          Calculator: File;
        };
      };
    };
  };
};

export const files: Files = {
  Root: {
    id: generateUniqueId(),
    icon: "",
    selected: false,
    animated: false,
    editable: false,
    index: 0,
    type: "directory",
    extension: "",
    component: "",
    entries: {
      System: {
        id: generateUniqueId(),
        icon: "",
        selected: false,
        animated: false,
        editable: false,
        index: 0,
        type: "directory",
        extension: "",
        component: "",
        entries: {
          "File Manager": {
            id: generateUniqueId(),
            icon: "clipgrab.svg",
            selected: false,
            animated: false,
            editable: false,
            index: 0,
            type: "file",
            extension: "app",
            component: "FileManager",
            entries: {},
          },
          Calculator: {
            id: generateUniqueId(),
            icon: "calculator.svg",
            selected: false,
            animated: false,
            editable: false,
            index: 1,
            type: "file",
            extension: "app",
            component: "Calculator",
            entries: {},
          },
          Settings: {
            id: generateUniqueId(),
            icon: "application-default-icon.svg",
            selected: false,
            animated: false,
            editable: false,
            index: 1,
            type: "file",
            extension: "app",
            component: "Settings",
            entries: {},
          },
          Calendar: {
            id: generateUniqueId(),
            icon: "pspp.svg",
            selected: false,
            animated: false,
            editable: false,
            index: 1,
            type: "file",
            extension: "app",
            component: "Calendar",
            entries: {},
          },
          Mail: {
            id: generateUniqueId(),
            icon: "lettera.svg",
            selected: false,
            animated: false,
            editable: false,
            index: 1,
            type: "file",
            extension: "app",
            component: "Mail",
            entries: {},
          },
          // Map: {
          //   id: generateUniqueId(),
          //   icon: "mappa.svg",
          //   selected: false,
          //   animated: false,
          //   editable: false,
          //   index: 1,
          //   type: "file",
          //   extension: "app",
          //   component: "Settings",
          //   entries: {},
          // },
          Documentation: {
            id: generateUniqueId(),
            icon: "yakuake.svg",
            selected: false,
            animated: false,
            editable: false,
            index: 1,
            type: "file",
            extension: "app",
            component: "Documentation",
            entries: {},
          },
          // "Image Viewer": {
          //   id: generateUniqueId(),
          //   icon: "fluxgui.svg",
          //   selected: false,
          //   animated: false,
          //   editable: false,
          //   index: 1,
          //   type: "file",
          //   extension: "app",
          //   component: "Settings",
          //   entries: {},
          // },
          // "Media Player": {
          //   id: generateUniqueId(),
          //   icon: "smtube.svg",
          //   selected: false,
          //   animated: false,
          //   editable: false,
          //   index: 1,
          //   type: "file",
          //   extension: "app",
          //   component: "Settings",
          //   entries: {},
          // },
          // Contacts: {
          //   id: generateUniqueId(),
          //   icon: "linphone.svg",
          //   selected: false,
          //   animated: false,
          //   editable: false,
          //   index: 1,
          //   type: "file",
          //   extension: "app",
          //   component: "Settings",
          //   entries: {},
          // },
          Notes: {
            id: generateUniqueId(),
            icon: "emacs.svg",
            selected: false,
            animated: false,
            editable: false,
            index: 1,
            type: "file",
            extension: "app",
            component: "Notes",
            entries: {},
          },
          "Bug Report": {
            id: generateUniqueId(),
            icon: "bug.svg",
            selected: false,
            animated: false,
            editable: false,
            index: 1,
            type: "file",
            extension: "app",
            component: "BugReport",
            entries: {},
          },
          Clock: {
            id: generateUniqueId(),
            icon: "caprine.svg",
            selected: false,
            animated: false,
            editable: false,
            index: 1,
            type: "file",
            extension: "app",
            component: "Clock",
            entries: {},
          },
        },
      },
      Desktop: {
        id: generateUniqueId(),
        icon: "",
        selected: false,
        animated: false,
        editable: false,
        index: 0,
        type: "directory",
        extension: "",
        component: "",
        entries: {
          Dashboard: {
            id: generateUniqueId(),
            icon: "anoise.svg",
            selected: false,
            animated: false,
            editable: false,
            index: 0,
            type: "file",
            extension: "app",
            component: "Dashboard",
            entries: {},
          },
          Music: {
            id: generateUniqueId(),
            icon: "noise.svg",
            selected: false,
            animated: false,
            editable: false,
            index: 1,
            type: "file",
            extension: "app",
            component: "Music",
            entries: {},
          },
          Downloads: {
            id: generateUniqueId(),
            icon: "",
            selected: false,
            animated: false,
            editable: false,
            index: 2,
            type: "directory",
            extension: "",
            component: "",
            entries: {
              "Annual Summaries": {
                id: generateUniqueId(),
                icon: "",
                selected: false,
                animated: false,
                editable: false,
                index: 0,
                type: "directory",
                extension: "",
                component: "",
                entries: {
                  Monthly_Report_Oct2024: {
                    id: generateUniqueId(),
                    icon: "",
                    selected: false,
                    animated: false,
                    editable: false,
                    index: 0,
                    type: "file",
                    extension: "txt",
                    component: "",
                    entries: {},
                  },
                  Project_Status_Report_v1: {
                    id: generateUniqueId(),
                    icon: "",
                    selected: false,
                    animated: false,
                    editable: false,
                    index: 1,
                    type: "file",
                    extension: "txt",
                    component: "",
                    entries: {},
                  },
                  Financial_Report_Q3_2024: {
                    id: generateUniqueId(),
                    icon: "",
                    selected: false,
                    animated: false,
                    editable: false,
                    index: 2,
                    type: "file",
                    extension: "txt",
                    component: "",
                    entries: {},
                  },
                  Annual_Summary_Report_2024: {
                    id: generateUniqueId(),
                    icon: "",
                    selected: false,
                    animated: false,
                    editable: false,
                    index: 3,
                    type: "file",
                    extension: "txt",
                    component: "",
                    entries: {},
                  },
                },
              },
              Scripts: {
                id: generateUniqueId(),
                icon: "",
                selected: false,
                animated: false,
                editable: false,
                index: 1,
                type: "directory",
                extension: "",
                component: "",
                entries: {
                  app_controller: {
                    id: generateUniqueId(),
                    icon: "",
                    selected: false,
                    animated: false,
                    editable: false,
                    index: 0,
                    type: "file",
                    extension: "js",
                    component: "",
                    entries: {},
                  },
                  main_functions: {
                    id: generateUniqueId(),
                    icon: "",
                    selected: false,
                    animated: false,
                    editable: false,
                    index: 1,
                    type: "file",
                    extension: "py",
                    component: "",
                    entries: {},
                  },
                  user_auth_service: {
                    id: generateUniqueId(),
                    icon: "",
                    selected: false,
                    animated: false,
                    editable: false,
                    index: 2,
                    type: "file",
                    extension: "rb",
                    component: "",
                    entries: {},
                  },
                  database_connection: {
                    id: generateUniqueId(),
                    icon: "",
                    selected: false,
                    animated: false,
                    editable: false,
                    index: 3,
                    type: "file",
                    extension: "php",
                    component: "",
                    entries: {},
                  },
                },
              },
              "EthanHunt Resume Portfolio": {
                id: generateUniqueId(),
                icon: "",
                selected: false,
                animated: false,
                editable: false,
                index: 2,
                type: "directory",
                extension: "",
                component: "",
                entries: {
                  Resume: {
                    id: generateUniqueId(),
                    icon: "",
                    selected: false,
                    animated: false,
                    editable: false,
                    index: 0,
                    type: "directory",
                    extension: "",
                    component: "",
                    entries: {
                      EthanHunt_Resume: {
                        id: generateUniqueId(),
                        icon: "",
                        selected: false,
                        animated: false,
                        editable: false,
                        index: 0,
                        type: "file",
                        extension: "pdf",
                        component: "",
                        entries: {},
                      },
                      EthanHunt_Portfolio_2045: {
                        id: generateUniqueId(),
                        icon: "",
                        selected: false,
                        animated: false,
                        editable: false,
                        index: 1,
                        type: "file",
                        extension: "pdf",
                        component: "",
                        entries: {},
                      },
                    },
                  },
                  Portfolio: {
                    id: generateUniqueId(),
                    icon: "",
                    selected: false,
                    animated: false,
                    editable: false,
                    index: 1,
                    type: "directory",
                    extension: "",
                    component: "",
                    entries: {
                      Ethan_Hunt_Experience_Summary: {
                        id: generateUniqueId(),
                        icon: "",
                        selected: false,
                        animated: false,
                        editable: false,
                        index: 0,
                        type: "file",
                        extension: "docx",
                        component: "",
                        entries: {},
                      },
                      Hunt_Ethan_JobApplication_Resume: {
                        id: generateUniqueId(),
                        icon: "",
                        selected: false,
                        animated: false,
                        editable: false,
                        index: 1,
                        type: "file",
                        extension: "pdf",
                        component: "",
                        entries: {},
                      },
                    },
                  },
                },
              },
            },
          },
          // Cineflix: {
          //   id: generateUniqueId(),
          //   icon: "anoise.svg",
          //   selected: false,
          //   animated: false,
          //   editable: false,
          //   index: 0,
          //   type: "file",
          //   extension: "app",
          //   component: "Settings",
          //   entries: {},
          // },
          // Tuneify: {
          //   id: generateUniqueId(),
          //   icon: "noise.svg",
          //   selected: false,
          //   animated: false,
          //   editable: false,
          //   index: 1,
          //   type: "file",
          //   extension: "app",
          //   component: "Settings",
          //   entries: {},
          // },
          // TalentHub: {
          //   id: generateUniqueId(),
          //   icon: "hamster.svg",
          //   selected: false,
          //   animated: false,
          //   editable: false,
          //   index: 2,
          //   type: "file",
          //   extension: "app",
          //   component: "Settings",
          //   entries: {},
          // },
        },
      },
      Documents: {
        id: generateUniqueId(),
        icon: "",
        selected: false,
        animated: false,
        editable: false,
        index: 0,
        type: "directory",
        extension: "",
        component: "",
        entries: {},
      },
      Downloads: {
        id: generateUniqueId(),
        icon: "",
        selected: false,
        animated: false,
        editable: false,
        index: 0,
        type: "directory",
        extension: "",
        component: "",
        entries: {},
      },
      Network: {
        id: generateUniqueId(),
        icon: "",
        selected: false,
        animated: false,
        editable: false,
        index: 0,
        type: "directory",
        extension: "",
        component: "",
        entries: {},
      },
      Shared: {
        id: generateUniqueId(),
        icon: "",
        selected: false,
        animated: false,
        editable: false,
        index: 0,
        type: "directory",
        extension: "",
        component: "",
        entries: {},
      },
      Trash: {
        id: generateUniqueId(),
        icon: "",
        selected: false,
        animated: false,
        editable: false,
        index: 0,
        type: "directory",
        extension: "",
        component: "",
        entries: {},
      },
    },
  },
};
