<?php

// Variables
return [
    'creatorName' => 'CZ App Studio',
    'creatorUrl' => 'https://czappstudio.com/',
    'supportNumber' => '+91 88254 29360',
    'supportWhatsappURL' => 'https://wa.me/+918825429360',
    'supportEmail' => 'support@czappstudio.com',
    'templateName' => 'Open Core BS',
    'templateFullName' => 'Open Core BS',
    'templateSuffix' => 'Open Source BS',
    'templateVersion' => '5.0.1',
    'templateFree' => false,
    'templateDescription' => 'Comprehensive Business Management Platform with 30+ Integrated Modules',
    'templateKeyword' => 'HRMS, HR, Management, System, Application, Software, Employee, Leave, Attendance, Payroll, Recruitment, Performance, Appraisal, Training, Development, Expense, Management, Task, Project, Team, Collaboration, Communication, Notification, Workflow, Automation, Reporting, Analytics, Dashboard, Admin, Panel',
    'licenseUrl' => 'https://czappstudio.com/license/',
    'livePreview' => 'https://czappstudio.com',
    'productPage' => 'https://czappstudio.com',
    'support' => 'https://czappstudio.com/support/',
    'activationDocs' => 'https://czappstudio.com/docs/open-core-hr/product-activation/',
    'moreThemes' => 'https://czappstudio.com',
    'documentation' => 'https://czappstudio.com/docs/open-core-hr/',
    'changelog' => 'https://czappstudio.com',
    'repository' => 'https://czappstudio.com',
    'gitRepo' => 'https://czappstudio.com',
    'gitRepoAccess' => 'https://czappstudio.com',
    'githubFreeUrl' => 'https://czappstudio.com',
    'facebookUrl' => 'https://czappstudio.com',
    'twitterUrl' => 'https://czappstudio.com',
    'githubUrl' => 'https://czappstudio.com',
    'dribbbleUrl' => 'https://czappstudio.com',
    'instagramUrl' => 'https://www.instagram.com/czappstudio/',
    'linkedInUrl' => 'https://in.linkedin.com/company/cz-app-studio',
    'youtubeUrl' => 'https://www.youtube.com/@CZAppStudio',
    'appDemoLink' => 'https://drive.google.com/file/d/1na1Cy-CaRdkFy2YF3o_RfLUgg4zcugyn/view?usp=sharing',
    'superAdminPanelDemoLink' => 'https://opencorebs.czappstudio.com/',
    'adminPanelDemoLink' => 'https://opencorebs.czappstudio.com/',
    'itemId' => 8849,
    'envatoItemId' => 50190332,
    'purchaseUrl' => 'https://codecanyon.net/item/field-manager-laravel-flutter-field-employee-tracking-complete-hrms-solution-android-ios/50190332',
    'addonsUrl' => 'https://czappstudio.com/open-core-bs-addons/',
];
